// eslint.config.mjs - ESLint flat config (ESLint 9) for the ALICE Next.js App Router app.
// Added by kanban task t_95d7f790. Pairs with the installed next@16.2.4; Next 16 removed
// `next lint`, so ESLint is driven directly by the existing `npm run lint` -> `eslint .`.
//
// Baseline when this gate was first installed (2026-10-10, tree at cb3ac3a):
//   130 files linted, 34 with findings, 102 problems = 73 errors / 29 warnings.
// Every rule exception below is a documented, visible downgrade or a scoped rule-off.
// Nothing here ignores real source: downgraded rules still print their findings as
// warnings on every run, so the debt stays in the totals instead of disappearing.
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,

  // --- Rule exceptions (each one deliberate; see documentation.md section 13.4) ---
  {
    rules: {
      // 0 sites after lint rank 8h (2026-10-10, card t_75b9c1b0): the last 8 —
      // components/vignette-generator.tsx (7) and components/tasks/DynamicTaskForm.tsx (1),
      // recorded findings since rank 8e because removing them surfaced genuine payload-shape
      // errors — were cleared by modelling `practice_package` and `form_data` as the unions the
      // app already writes (`StoredPracticeTask` in lib/practice-package.ts, `SubmissionFormData`
      // in types/tasks.ts). Dead downgrade; deleting it is a rule change that no card carries,
      // so it stays and is an open operator decision, on the same standing as react-hooks/refs
      // and react-hooks/purity below.
      "@typescript-eslint/no-explicit-any": "warn",
      // 4 sites across 3 files after lint rank 8g (2026-10-10, card t_2d4d0225), all four
      // DELIBERATELY RETAINED with a written reason in the source: components/tasks/
      // DynamicTaskForm.tsx holds two (the externalSubmissionId mirror, register row B11, and
      // the debounced autosave, B12), components/vignette-generator.tsx one (B13, the
      // session-hydration latch the 15 hydration-guard checks pin) and hooks/
      // use-clinical-workspace.ts one (B15, a guarded derived-default in a hook with zero
      // importers). Rank 8g cleared the other 7 sites and row B10's exhaustive-deps finding
      // (the four fetch-derived loaders, the drawer close, and the two matchMedia
      // subscriptions), so the downgrade stays only while these four recorded findings remain:
      // a rule may not stop being downgraded while any site is left.
      "react-hooks/set-state-in-effect": "warn",
      // 0 sites since lint rank 8c fixed the one read (components/canvas/ReflectionCanvas.tsx).
      // Dead downgrade; deleting it is a rule change that no card carries, so it stays and is
      // an open operator decision.
      "react-hooks/refs": "warn",
      // 0 sites since lint rank 8d deleted components/ui/sidebar.tsx (the Math.random site).
      // Dead downgrade, same standing as react-hooks/refs above.
      "react-hooks/purity": "warn",
      // 0 sites after lint rank 8f (2026-10-10) escaped both apostrophes (app/forgot-password/
      // page.tsx and components/tasks/ThreeCsForm.tsx). Dead downgrade, same standing as the
      // two above.
      "react/no-unescaped-entities": "warn",
    },
  },

  // The two Worker entry points — backend/CloudFlare.js and workers/mcp-gateway/src/index.ts —
  // export the module-worker shape `export default { async fetch(request, env) { … } }`. That
  // object literal is what `wrangler` requires and its members are named, so the rule's rationale
  // (named exports for readable stack traces) is satisfied. `allowObject: true` scopes the
  // exemption to object-literal default exports only: an anonymous `export default function() {}`
  // inside these globs still reports.
  {
    files: ["backend/**/*.js", "workers/**/*.ts"],
    rules: { "import/no-anonymous-default-export": ["warn", { allowObject: true }] },
  },

  // The Cloudflare Worker entry (backend/CloudFlare.js) is plain JS shipped with an explicit
  // `@ts-nocheck` header; that is the file documented contract, not an accident.
  {
    files: ["backend/**/*.js"],
    rules: { "@typescript-eslint/ban-ts-comment": "off" },
  },

  globalIgnores([
    // Build output
    ".next/**",
    // Dependencies
    "node_modules/**",
    // Generated / vendored Worker bundles and wrangler scratch state
    "backend/.wrangler/**",
    "backend/deployed/**",
    // Verification-harness report bundles and screenshots
    "debug_reports/**",
    // Obsidian sync copy of documentation.md
    ".obsidian_sync/**",
    // Local scratch workspace (untracked)
    "scratch/**",
    // Generated by next dev/build
    "next-env.d.ts",
  ]),
]);
