// eslint.config.mjs - ESLint flat config (ESLint 9) for the ALICE Next.js App Router app.
// Added by kanban task t_95d7f790. Pairs with the installed next@16.2.4; Next 16 removed
// `next lint`, so ESLint is driven directly by the existing `npm run lint` -> `eslint .`.
//
// Baseline when this gate was first installed (2026-10-10, tree at cb3ac3a):
//   130 files linted, 34 with findings, 102 problems = 73 errors / 29 warnings.
// Every rule exception below is a documented, visible downgrade or a scoped rule-off.
// Nothing here ignores real source: downgraded rules still print their findings as
// warnings on every run, so the debt stays in the totals instead of disappearing.
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,

  // --- Rule exceptions (each one deliberate; see documentation.md section 13.4) ---
  // Four dead downgrades were removed from this block on 2026-10-10 (lint rank 8k, card
  // t_0c86d33b, operator-approved): `@typescript-eslint/no-explicit-any` (0 sites since rank 8h),
  // `react-hooks/refs` (0 since rank 8c), `react-hooks/purity` (0 since rank 8d) and
  // `react/no-unescaped-entities` (0 since rank 8f). Each sat at `warn` here where the extended
  // configs assign `error`; the restored severity was measured, not assumed — `eslint
  // --print-config` against a probe config without this block reports severity 2 for all four
  // against 1 with it. Zero findings were reported by any of the four on the tree at removal, so
  // deleting them restored the real severity without changing a single reported finding. The
  // consequence is intended and is stated in documentation.md section 13.4: a future ref read
  // during render, a `Math.random()` in render, an unescaped apostrophe in JSX text or a new
  // `any` now FAILS `npm run lint` instead of warning.
  {
    rules: {
      // 3 sites across 2 files after lint rank 8l (2026-10-10, card t_b32676c6), all three
      // DELIBERATELY RETAINED with a written reason in the source: components/tasks/
      // DynamicTaskForm.tsx holds two (the externalSubmissionId mirror, register row B11, and
      // the debounced autosave, B12) and components/vignette-generator.tsx one (B13, the
      // session-hydration latch the 15 hydration-guard checks pin). The fourth was row B15,
      // hooks/use-clinical-workspace.ts (a guarded derived-default in a hook with zero
      // importers) — that file was archived as unreferenced at rank 8l, and its finding left
      // the totals with it, because `archive/**` is in `globalIgnores` below. Nothing is hidden
      // by this: the file is no longer linted as live source, which is the point of the archive.
      // Rank 8g cleared the other 7 sites and row B10's exhaustive-deps finding (the four
      // fetch-derived loaders, the drawer close, and the two matchMedia subscriptions), so the
      // downgrade stays only while these three recorded findings remain: a rule may not stop
      // being downgraded while any site is left.
      "react-hooks/set-state-in-effect": "warn",
    },
  },

  // The two Worker entry points — backend/CloudFlare.js and workers/mcp-gateway/src/index.ts —
  // export the module-worker shape `export default { async fetch(request, env) { … } }`. That
  // object literal is what `wrangler` requires and its members are named, so the rule's rationale
  // (named exports for readable stack traces) is satisfied. `allowObject: true` scopes the
  // exemption to object-literal default exports only: an anonymous `export default function() {}`
  // inside these globs still reports.
  {
    files: ["backend/**/*.js", "workers/**/*.ts"],
    rules: { "import/no-anonymous-default-export": ["warn", { allowObject: true }] },
  },

  // The Cloudflare Worker entry (backend/CloudFlare.js) is plain JS shipped with an explicit
  // `@ts-nocheck` header; that is the file documented contract, not an accident.
  {
    files: ["backend/**/*.js"],
    rules: { "@typescript-eslint/ban-ts-comment": "off" },
  },

  globalIgnores([
    // Build output
    ".next/**",
    // Dependencies
    "node_modules/**",
    // Generated / vendored Worker bundles and wrangler scratch state
    "backend/.wrangler/**",
    "backend/deployed/**",
    // Verification-harness report bundles and screenshots
    "debug_reports/**",
    // Obsidian sync copy of documentation.md
    ".obsidian_sync/**",
    // Local scratch workspace (untracked)
    "scratch/**",
    // Generated by next dev/build
    "next-env.d.ts",
    // Archived-but-not-live sources (2026-10-10, card t_09ae9f3d): moved here, not deleted, so they
    // cannot rot or come back as live code by accident. Ignored so `eslint .` keeps matching exactly
    // the live tree; see archive/2026-10-10-unreferenced-ui-kit/README.md
    "archive/**",
  ]),
]);
