"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { CLINICAL_AI_API_BASE } from "@/lib/clinical-ai-api";

type PracticePackage = {
  homework: any[];
};

type SessionData = {
  id?: string;
  name?: string;
  practicePackage?: PracticePackage | null;
};

export default function PracticePage() {
  const params = useParams();

  const sessionId =
    typeof params?.sessionId === "string"
      ? params.sessionId
      : Array.isArray(params?.sessionId)
      ? params.sessionId[0]
      : null;

  const [loading, setLoading] = useState(true);
  const [session, setSession] =
    useState<SessionData | null>(null);

  const [error, setError] =
    useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      if (!sessionId) {
        setError("Missing session ID");
        setLoading(false);
        return;
      }

      try {
        const res = await fetch(
          `${CLINICAL_AI_API_BASE}/sessions/${sessionId}`,
          {
            method: "GET",
            cache: "no-store",
          }
        );

        const data = await res.json();

        if (!res.ok) {
          throw new Error(
            data?.error || "Failed to load session"
          );
        }

        setSession({
          id: data.id,
          name: data.name,
          practicePackage:
            data.practicePackage || null,
        });

        setError(null);
      } catch (err: any) {
        setError(
          err?.message ||
            "Unable to load practice tasks"
        );
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [sessionId]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        Loading...
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center text-red-500">
        {error}
      </div>
    );
  }

  const homework =
    session?.practicePackage?.homework || [];

  return (
    <div className="min-h-screen bg-gray-50 flex justify-center">
      <div className="w-full max-w-2xl px-6 py-10">

        <div className="bg-white border rounded-xl p-8 shadow-sm">

          <h1 className="text-2xl font-semibold text-center mb-3">
            Client Practice Task
          </h1>

          <p className="text-center text-gray-500 mb-8">
            Please complete the following tasks before your next session
          </p>

          {homework.length === 0 ? (
            <div className="text-center text-gray-400">
              No practice tasks available.
            </div>
          ) : (
            <div className="space-y-5">
              {homework.map(
                (item: any, index: number) => (
                  <div
                    key={index}
                    className="flex items-start gap-3"
                  >
                    <span className="text-lg">
                      ☐
                    </span>

                    <span className="text-gray-700">
                      {typeof item === "string"
                        ? item
                        : item.task}
                    </span>
                  </div>
                )
              )}
            </div>
          )}

          <div className="mt-10 text-center text-xs text-gray-400">
            Generated by ALICE 
          </div>

        </div>
      </div>
    </div>
  );
}